Add ISCE3 Installation Script, Help Script Subcommand Dispatcher, and OnDemand System Activity Tracker
isce-framework/sds-ondemand pull request #18
Opened 2024-08-29 23:48 UTC by nerivera

This PR introduces several significant features and improvements to the project, as part of the work completed during my internship at JPL. The changes include the addition of an installation script for ISCE3, a subcommand dispatcher for a help script, and an activity tracker for the OnDemand System running on the CI machine (Jenkins).

2024-08-30 18:44 UTC, jplzhan requested changes
There are a couple places we would like to remove the hardcoding of bucket names and the help email, which will make it easier to adapt this script to other OnDemand systems if these names change.

2024-08-30 18:44 UTC, jplzhan commented on activity_tracker/1-download-data.sh
Please adjust the bucket name here to be an environment variable.

2024-08-30 18:44 UTC, jplzhan commented on activity_tracker/2-update-data.py
> +* If you have questions, please email the nisar-ondemand-help@jpl.nasa.gov address for assistance.                 \n\
Please adjust the email here to be an environment variable.

2024-08-30 18:44 UTC, jplzhan commented on activity_tracker/3-upload-data.sh
> +aws s3 cp ./usage-history.csv s3://nisar-st-data-ondemand/Ondemand_Logs/Activity_Tracker/usage-history.csv
Please adjust the bucket names here to be an environment variable.

2024-08-30 18:44 UTC, jplzhan commented on activity_tracker/2-update-data.py
> +* If you have questions, please email the nisar-ondemand-help@jpl.nasa.gov address for assistance.                 \n\
Please change this email name to be an environment variable.

2024-09-01 01:55 UTC, nerivera commented
I've made the requested changes

2024-09-04 16:21 UTC, jplzhan approved these changes

2024-09-04 16:21 UTC, merged